\i users.sql
\i posts.sql
\i groups.sql
\i group_members.sql
\i relationships.sql
\i comments.sql
\i likes.sql
\i notifications.sql
\i reports.sql
\i chats.sql
\i chat_participants.sql
\i messages.sql
